In [1]:
from pathlib import Path
import json

import pandas as pd
from pandarallel import pandarallel

pandarallel.initialize(progress_bar=True)

INFO: Pandarallel will run on 64 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [2]:
files = Path("./data").glob("part-*.json")

df = pd.DataFrame()

for f in files:
    df_partial = pd.read_json(f, lines=True)
    df = pd.concat([df, df_partial], ignore_index=True)
    print(f"read {f}")

df

read data/part-00000-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00001-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00002-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00003-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00004-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00005-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00006-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00007-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00008-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json
read data/part-00009-905505be-27fc-4ec6-9fb3-3c3a9eee30c4-c000.json

,id,seq,is_moving,position,shape,orientation,velocity,type,heading,time_meas
0,171547107,280384074,0,"{""x"":-97.084885,""y"":-232.3759}","{""x"":4.7983685,""y"":1.9409764,""z"":1.477407}",-1.956837,0.000000,1,-1.956837,1681316587212111
1,174982399,280378832,1,"{""x"":-81.32461,""y"":-205.8905,""z"":12.71776}","{""x"":4.8877726,""y"":2.066351,""z"":1.6486948}",-1.951671,11.150774,1,-1.951671,1681316063099694
2,172577571,280370972,0,"{""x"":-102.30659,""y"":-243.60515}","{""x"":4.6133704,""y"":1.8898311,""z"":1.5328883}",1.172874,0.000000,1,-1.956837,1681315277099689
3,175295560,280384752,0,"{""x"":47.18,""y"":-139.38}","{""x"":0.2,""y"":0.2,""z"":0.3402624}",0.000000,0.000000,7,0.000000,1681316655099830
4,174502019,280381808,0,"{""x"":-127.55312,""y"":-299.1321}","{""x"":5.058619,""y"":2.312317,""z"":2.168332}",-1.955391,0.000000,1,-1.955391,1681316360699765
...,...,...,...,...,...,...,...,...,...,...
16352061,312862933,281216302,0,"{""x"":-105.99032,""y"":-251.68732}","{""x"":4.538488,""y"":1.9699273,""z"":1.5516202}",-1.956837,0.000000,1,-1.956837,1681399810099905
16352062,325893347,281219454,1,"{""x"":-85.87409,""y"":-215.58902,""z"":12.853886}","{""x"":4.459084,""y"":1.9285438,""z"":1.6981514}",-1.958847,5.690683,1,-1.958847,1681400125299717
16352063,321051342,281221514,0,"{""x"":-113.88043,""y"":-267.3889}","{""x"":4.357365,""y"":1.8757665,""z"":1.6364138}",-1.956837,0.000000,1,-1.956837,1681400331299724
16352064,323320565,281219118,0,"{""x"":-95.94897,""y"":-229.30392}","{""x"":4.6600776,""y"":2.0072696,""z"":1.6873806}",-1.956284,0.000000,1,-1.956284,1681400091699641
16352065,321658899,281221538,0,"{""x"":-28.221827,""y"":-42.18834}","{""x"":8.884403,""y"":2.9622433,""z"":3.5429688}",-2.007512,0.000000,4,-2.007512,1681400333699776

In [3]:
df = df[df["seq"] > 0]
df

,id,seq,is_moving,position,shape,orientation,velocity,type,heading,time_meas
0,171547107,280384074,0,"{""x"":-97.084885,""y"":-232.3759}","{""x"":4.7983685,""y"":1.9409764,""z"":1.477407}",-1.956837,0.000000,1,-1.956837,1681316587212111
1,174982399,280378832,1,"{""x"":-81.32461,""y"":-205.8905,""z"":12.71776}","{""x"":4.8877726,""y"":2.066351,""z"":1.6486948}",-1.951671,11.150774,1,-1.951671,1681316063099694
2,172577571,280370972,0,"{""x"":-102.30659,""y"":-243.60515}","{""x"":4.6133704,""y"":1.8898311,""z"":1.5328883}",1.172874,0.000000,1,-1.956837,1681315277099689
3,175295560,280384752,0,"{""x"":47.18,""y"":-139.38}","{""x"":0.2,""y"":0.2,""z"":0.3402624}",0.000000,0.000000,7,0.000000,1681316655099830
4,174502019,280381808,0,"{""x"":-127.55312,""y"":-299.1321}","{""x"":5.058619,""y"":2.312317,""z"":2.168332}",-1.955391,0.000000,1,-1.955391,1681316360699765
...,...,...,...,...,...,...,...,...,...,...
16352061,312862933,281216302,0,"{""x"":-105.99032,""y"":-251.68732}","{""x"":4.538488,""y"":1.9699273,""z"":1.5516202}",-1.956837,0.000000,1,-1.956837,1681399810099905
16352062,325893347,281219454,1,"{""x"":-85.87409,""y"":-215.58902,""z"":12.853886}","{""x"":4.459084,""y"":1.9285438,""z"":1.6981514}",-1.958847,5.690683,1,-1.958847,1681400125299717
16352063,321051342,281221514,0,"{""x"":-113.88043,""y"":-267.3889}","{""x"":4.357365,""y"":1.8757665,""z"":1.6364138}",-1.956837,0.000000,1,-1.956837,1681400331299724
16352064,323320565,281219118,0,"{""x"":-95.94897,""y"":-229.30392}","{""x"":4.6600776,""y"":2.0072696,""z"":1.6873806}",-1.956284,0.000000,1,-1.956284,1681400091699641
16352065,321658899,281221538,0,"{""x"":-28.221827,""y"":-42.18834}","{""x"":8.884403,""y"":2.9622433,""z"":3.5429688}",-2.007512,0.000000,4,-2.007512,1681400333699776

In [4]:
cnt = df.groupby("id")["type"].nunique().reset_index()
df = df[df["id"].isin(cnt[cnt["type"] == 1]["id"])]
df

,id,seq,is_moving,position,shape,orientation,velocity,type,heading,time_meas
0,171547107,280384074,0,"{""x"":-97.084885,""y"":-232.3759}","{""x"":4.7983685,""y"":1.9409764,""z"":1.477407}",-1.956837,0.000000,1,-1.956837,1681316587212111
1,174982399,280378832,1,"{""x"":-81.32461,""y"":-205.8905,""z"":12.71776}","{""x"":4.8877726,""y"":2.066351,""z"":1.6486948}",-1.951671,11.150774,1,-1.951671,1681316063099694
2,172577571,280370972,0,"{""x"":-102.30659,""y"":-243.60515}","{""x"":4.6133704,""y"":1.8898311,""z"":1.5328883}",1.172874,0.000000,1,-1.956837,1681315277099689
3,175295560,280384752,0,"{""x"":47.18,""y"":-139.38}","{""x"":0.2,""y"":0.2,""z"":0.3402624}",0.000000,0.000000,7,0.000000,1681316655099830
4,174502019,280381808,0,"{""x"":-127.55312,""y"":-299.1321}","{""x"":5.058619,""y"":2.312317,""z"":2.168332}",-1.955391,0.000000,1,-1.955391,1681316360699765
...,...,...,...,...,...,...,...,...,...,...
16352061,312862933,281216302,0,"{""x"":-105.99032,""y"":-251.68732}","{""x"":4.538488,""y"":1.9699273,""z"":1.5516202}",-1.956837,0.000000,1,-1.956837,1681399810099905
16352062,325893347,281219454,1,"{""x"":-85.87409,""y"":-215.58902,""z"":12.853886}","{""x"":4.459084,""y"":1.9285438,""z"":1.6981514}",-1.958847,5.690683,1,-1.958847,1681400125299717
16352063,321051342,281221514,0,"{""x"":-113.88043,""y"":-267.3889}","{""x"":4.357365,""y"":1.8757665,""z"":1.6364138}",-1.956837,0.000000,1,-1.956837,1681400331299724
16352064,323320565,281219118,0,"{""x"":-95.94897,""y"":-229.30392}","{""x"":4.6600776,""y"":2.0072696,""z"":1.6873806}",-1.956284,0.000000,1,-1.956284,1681400091699641
16352065,321658899,281221538,0,"{""x"":-28.221827,""y"":-42.18834}","{""x"":8.884403,""y"":2.9622433,""z"":3.5429688}",-2.007512,0.000000,4,-2.007512,1681400333699776

In [5]:
df.loc[:,"position"] = df["position"].parallel_apply(json.loads)
df

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=242931), Label(value='0 / 242931')â€¦

,id,seq,is_moving,position,shape,orientation,velocity,type,heading,time_meas
0,171547107,280384074,0,"{'x': -97.084885, 'y': -232.3759}","{""x"":4.7983685,""y"":1.9409764,""z"":1.477407}",-1.956837,0.000000,1,-1.956837,1681316587212111
1,174982399,280378832,1,"{'x': -81.32461, 'y': -205.8905, 'z': 12.71776}","{""x"":4.8877726,""y"":2.066351,""z"":1.6486948}",-1.951671,11.150774,1,-1.951671,1681316063099694
2,172577571,280370972,0,"{'x': -102.30659, 'y': -243.60515}","{""x"":4.6133704,""y"":1.8898311,""z"":1.5328883}",1.172874,0.000000,1,-1.956837,1681315277099689
3,175295560,280384752,0,"{'x': 47.18, 'y': -139.38}","{""x"":0.2,""y"":0.2,""z"":0.3402624}",0.000000,0.000000,7,0.000000,1681316655099830
4,174502019,280381808,0,"{'x': -127.55312, 'y': -299.1321}","{""x"":5.058619,""y"":2.312317,""z"":2.168332}",-1.955391,0.000000,1,-1.955391,1681316360699765
...,...,...,...,...,...,...,...,...,...,...
16352061,312862933,281216302,0,"{'x': -105.99032, 'y': -251.68732}","{""x"":4.538488,""y"":1.9699273,""z"":1.5516202}",-1.956837,0.000000,1,-1.956837,1681399810099905
16352062,325893347,281219454,1,"{'x': -85.87409, 'y': -215.58902, 'z': 12.853886}","{""x"":4.459084,""y"":1.9285438,""z"":1.6981514}",-1.958847,5.690683,1,-1.958847,1681400125299717
16352063,321051342,281221514,0,"{'x': -113.88043, 'y': -267.3889}","{""x"":4.357365,""y"":1.8757665,""z"":1.6364138}",-1.956837,0.000000,1,-1.956837,1681400331299724
16352064,323320565,281219118,0,"{'x': -95.94897, 'y': -229.30392}","{""x"":4.6600776,""y"":2.0072696,""z"":1.6873806}",-1.956284,0.000000,1,-1.956284,1681400091699641
16352065,321658899,281221538,0,"{'x': -28.221827, 'y': -42.18834}","{""x"":8.884403,""y"":2.9622433,""z"":3.5429688}",-2.007512,0.000000,4,-2.007512,1681400333699776

In [6]:
df.loc[:,"shape"] = df["shape"].parallel_apply(json.loads)
df

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=242931), Label(value='0 / 242931')â€¦

,id,seq,is_moving,position,shape,orientation,velocity,type,heading,time_meas
0,171547107,280384074,0,"{'x': -97.084885, 'y': -232.3759}","{'x': 4.7983685, 'y': 1.9409764, 'z': 1.477407}",-1.956837,0.000000,1,-1.956837,1681316587212111
1,174982399,280378832,1,"{'x': -81.32461, 'y': -205.8905, 'z': 12.71776}","{'x': 4.8877726, 'y': 2.066351, 'z': 1.6486948}",-1.951671,11.150774,1,-1.951671,1681316063099694
2,172577571,280370972,0,"{'x': -102.30659, 'y': -243.60515}","{'x': 4.6133704, 'y': 1.8898311, 'z': 1.5328883}",1.172874,0.000000,1,-1.956837,1681315277099689
3,175295560,280384752,0,"{'x': 47.18, 'y': -139.38}","{'x': 0.2, 'y': 0.2, 'z': 0.3402624}",0.000000,0.000000,7,0.000000,1681316655099830
4,174502019,280381808,0,"{'x': -127.55312, 'y': -299.1321}","{'x': 5.058619, 'y': 2.312317, 'z': 2.168332}",-1.955391,0.000000,1,-1.955391,1681316360699765
...,...,...,...,...,...,...,...,...,...,...
16352061,312862933,281216302,0,"{'x': -105.99032, 'y': -251.68732}","{'x': 4.538488, 'y': 1.9699273, 'z': 1.5516202}",-1.956837,0.000000,1,-1.956837,1681399810099905
16352062,325893347,281219454,1,"{'x': -85.87409, 'y': -215.58902, 'z': 12.853886}","{'x': 4.459084, 'y': 1.9285438, 'z': 1.6981514}",-1.958847,5.690683,1,-1.958847,1681400125299717
16352063,321051342,281221514,0,"{'x': -113.88043, 'y': -267.3889}","{'x': 4.357365, 'y': 1.8757665, 'z': 1.6364138}",-1.956837,0.000000,1,-1.956837,1681400331299724
16352064,323320565,281219118,0,"{'x': -95.94897, 'y': -229.30392}","{'x': 4.6600776, 'y': 2.0072696, 'z': 1.6873806}",-1.956284,0.000000,1,-1.956284,1681400091699641
16352065,321658899,281221538,0,"{'x': -28.221827, 'y': -42.18834}","{'x': 8.884403, 'y': 2.9622433, 'z': 3.5429688}",-2.007512,0.000000,4,-2.007512,1681400333699776

In [10]:
df.loc[:,"time"] = pd.to_datetime(df["time_meas"], unit="us", origin="unix")
df = df.drop("time_meas", axis=1)
df

,id,seq,is_moving,position,shape,orientation,velocity,type,heading,time
0,171547107,280384074,0,"{'x': -97.084885, 'y': -232.3759}","{'x': 4.7983685, 'y': 1.9409764, 'z': 1.477407}",-1.956837,0.000000,1,-1.956837,2023-04-12 16:23:07.212111
1,174982399,280378832,1,"{'x': -81.32461, 'y': -205.8905, 'z': 12.71776}","{'x': 4.8877726, 'y': 2.066351, 'z': 1.6486948}",-1.951671,11.150774,1,-1.951671,2023-04-12 16:14:23.099694
2,172577571,280370972,0,"{'x': -102.30659, 'y': -243.60515}","{'x': 4.6133704, 'y': 1.8898311, 'z': 1.5328883}",1.172874,0.000000,1,-1.956837,2023-04-12 16:01:17.099689
3,175295560,280384752,0,"{'x': 47.18, 'y': -139.38}","{'x': 0.2, 'y': 0.2, 'z': 0.3402624}",0.000000,0.000000,7,0.000000,2023-04-12 16:24:15.099830
4,174502019,280381808,0,"{'x': -127.55312, 'y': -299.1321}","{'x': 5.058619, 'y': 2.312317, 'z': 2.168332}",-1.955391,0.000000,1,-1.955391,2023-04-12 16:19:20.699765
...,...,...,...,...,...,...,...,...,...,...
16352061,312862933,281216302,0,"{'x': -105.99032, 'y': -251.68732}","{'x': 4.538488, 'y': 1.9699273, 'z': 1.5516202}",-1.956837,0.000000,1,-1.956837,2023-04-13 15:30:10.099905
16352062,325893347,281219454,1,"{'x': -85.87409, 'y': -215.58902, 'z': 12.853886}","{'x': 4.459084, 'y': 1.9285438, 'z': 1.6981514}",-1.958847,5.690683,1,-1.958847,2023-04-13 15:35:25.299717
16352063,321051342,281221514,0,"{'x': -113.88043, 'y': -267.3889}","{'x': 4.357365, 'y': 1.8757665, 'z': 1.6364138}",-1.956837,0.000000,1,-1.956837,2023-04-13 15:38:51.299724
16352064,323320565,281219118,0,"{'x': -95.94897, 'y': -229.30392}","{'x': 4.6600776, 'y': 2.0072696, 'z': 1.6873806}",-1.956284,0.000000,1,-1.956284,2023-04-13 15:34:51.699641
16352065,321658899,281221538,0,"{'x': -28.221827, 'y': -42.18834}","{'x': 8.884403, 'y': 2.9622433, 'z': 3.5429688}",-2.007512,0.000000,4,-2.007512,2023-04-13 15:38:53.699776

In [14]:
df.to_parquet("./cleaned_data/road_data.parquet", index=False)